### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by jpontius** [msmith91/google_traffic#1]
I've updated traffic_times.py with my api key and addresses.  Now I'm getting this error when trying to run: 

```
File "traffic_times.py", line 24
    json_url = urllib.urlopen(url).read()
    ^
IndentationError: unexpected indent
```

**Comment by Kickball** [comment]
It seems the indentation is a little off with parts of the script I'll submit a PR with a fix within the hour.

**Comment by msmith91** [comment]
I've updated the spacing to 4 spaces.  I had some sort of mixture  of tabs and spaces that might have been causing issues.  Let me know how it works for you.

Thanks!

**Comment by Kickball** [comment]
#2 should fix any formatting issues in the Python script.

**Comment by msmith91** [comment]
Let me know if the edits Kickball made do not fix your issues, Jpontius, and I'll reopen the ticket.
