### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by Kickball** [msmith91/google_traffic#3]
Generally speaking, the absence of a license means that default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. - [Github](http://choosealicense.com/no-license/)

A license should be added to the project, consider using [this](http://choosealicense.com/) or [this](https://creativecommons.org/choose/) to help with license selection.

**Comment by msmith91** [comment]
Thanks for your help.  I'm new to Github (as you can likely tell).  I've added an open-use license.  I'd love to hear how you use any of this code if you find it useful!

**Comment by Kickball** [comment]
I'll give some feedback once I've had chance to use it some more.

I've got a big PR in the works which is just waiting on #3.
